name: Build packages
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Build packages
      run: |
        cat << EOF > entrypoint.sh
        set -e
        cd /build
        echo '[mbp]
        Server = https://dl.t2linux.org/archlinux/\$repo/\$arch' >> /etc/pacman.conf
        pacman-key --init
        curl -o key.asc https://dl.t2linux.org/archlinux/key.asc
        pacman-key --add key.asc
        pacman-key --lsign 7F9B8FC29F78B339
        pacman -Syu --noconfirm --needed sudo base-devel linux-mbp linux-mbp-headers
        useradd builduser -m
        sudo -u builduser gpg --keyserver keyserver.ubuntu.com --recv-keys 38DBBDC86092693E
        passwd -d builduser
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser /build

        for i in apple-ibridge-dkms-git  apple-t2-audio-config  linux-t2; do
        cd \$i
        pwd
        sudo -u builduser bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -s --noconfirm'
        cd ..
        done

        cp */*.pkg.tar.* ./
        repo-add ./${{github.repository_owner}}-t2.db.tar.gz ./*.pkg.tar.*

        for i in *.db *.files; do
        cp --remove-destination \$(readlink \$i) \$i
        done

        EOF
        cat entrypoint.sh
        docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
        ls -l .
        
    - name: generate tag
      id: tag
      run: |
        count=$(git rev-list --count HEAD)
        hash=$(git rev-parse --short HEAD)
        echo "::set-output name=tag::r${count}.${hash}"
        
    - name: Print sha512sums
      run: sha512sum */*.pkg.tar.*

    - name: Upload Packages Artifact
      uses: actions/upload-artifact@v2
      with:
        name: t2-packages-${{ steps.tag.outputs.tag }}
        path: |
          ${{ github.workspace }}/*.pkg.tar.*
          ${{ github.workspace }}/*-t2.files*
          ${{ github.workspace }}/*-t2.db*

    - name: Release
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}/*.pkg.tar.*
          ${{ github.workspace }}/*-t2.files*
          ${{ github.workspace }}/*-t2.db*
        tag_name: repo #${{ steps.tag.outputs.tag }}
          #draft: ${{ contains(github.event.head_commit.message, '[draft]') }}
          #prerelease: ${{ contains(github.event.head_commit.message, '[pre]') }}
          #generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
